# ----
# Site

title: '#SayNoToFish'
url:
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /logo_transparent.png
description: Protect our planet, don't eat fish
author:
  name:
  email:
  twitter: SayNoToFish
social:
  name: '#SayNoToFish'
  links:


# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250
  news:
    output: true
    permalink: /:collection/:path/

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

# donation_embed: '<script src="https://donorbox.org/widget.js" type="text/javascript"></script><iframe src="https://donorbox.org/embed/give-sheep-the-vote?hide_donation_meter=true" height="685px" width="100%" style="max-width:425px; min-width:310px" seamless="seamless" id="dbox-form-embed" name="donorbox" frameborder="0" scrolling="no"></iframe>'
# newsletter_action: "https://saynotofish.us19.list-manage.com/subscribe/post?u=470e2801c26b3596289833a4d&amp;id=9605e4e3a5"

# Outputting
paginate: 3 # amount of posts to show
paginate_path: /news:num/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
